.docker-build-api:
  image: docker:latest
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:api-$CI_COMMIT_REF_NAME
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

build-api:
  extends:
    - .docker-build-api
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:api-staging
  only:
    - develop
    - deploy/staging

deploy-staging:
  image: docker:latest
  stage: deploy
  timeout: 2h
  services:
    - docker:dind
  before_script:
    - apk update
    - apk add zip
    - 'which ssh-agent || ( apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$STAGING_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - chmod 700 ~/.ssh
  script:
    - >-
      $STAGING_SSH_CMD
      "cd $STAGING_WORK_DIR
      && docker compose pull fitivation-api-staging
      && docker compose up -d fitivation-api-staging
      && docker image prune -f
      && exit"
  only:
    - deploy/staging
